[package]
name = "py-perpetual"
version = "0.0.5"
edition = "2021"
authors = ["Mutlu Simsek <msimsek@perpetual-ml.com>"]
homepage = "https://perpetual-ml.com/docs"
description = "A self-generalizing, hyperparameter-free gradient boosting machine"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/perpetual-ml/perpetual"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "perpetual"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
perpetual_rs = {package="perpetual", version = "0.0.5", path = "../" }
numpy = "0.21.0"
ndarray = "0.15.1"
serde_plain = { version = "1.0" }
serde = { version = "1.0" }
pyo3-log = "0.10.0"
