[build-system]
requires = ["maturin>=1.0.0,<2.0.0"]
build-backend = "maturin"

[project]
name = "perpetual"
description = "A gradient boosting implementation in Rust."
license = { file = "LICENSE" }
keywords = [
  "rust",
  "perpetual",
  "machine learning",
  "tree model",
  "decision tree",
  "gradient boosted decision tree",
  "gradient boosting machine"
]
authors = [{ name = "Mutlu Simsek" }]
readme = "README.md"
dependencies = ["numpy>=1.21", "pandas>=2.0"]
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

[project.optional-dependencies]
dev = ["maturin", "pytest", "seaborn", "scikit-learn", "mkdocs-material==9.*", "mkdocstrings[python]==0.22.0", "mkdocs-autorefs", "ruff>=0.0.272", "ucimlrepo"]

[tool.maturin]
sdist-include = ["LICENSE", "README.md"]
python-source = "python"
module-name = "perpetual.perpetual"

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]

[tool.isort]
profile = "black"
